# Generated by Django 4.2 on 2023-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.EmailField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='license_type',
            field=models.CharField(choices=[('1', 'Individual'), ('2', 'Firm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='broker',
            name='rera_registered',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'I have applied'), ('3', 'Not Applicable')], max_length=10),
        ),
    ]
