# Generated by Django 4.2 on 2023-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_broker_email_alter_broker_license_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='user',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
