# Generated by Django 4.2 on 2023-04-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_broker_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
