# Generated by Django 4.2 on 2023-04-30 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype2',
            old_name='image_links',
            new_name='images_links',
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='property_sub_type',
            field=models.CharField(choices=[('resedential', 'Resedential'), ('commercial', 'Commercial')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='property_sub_type',
            field=models.CharField(choices=[('resedential', 'Resedential'), ('commercial', 'Commercial')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertytype2',
            name='availability_status',
            field=models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction')], max_length=20),
        ),
    ]
