# Generated by Django 4.2 on 2023-05-08 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0009_alter_propertytype3_possession_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype3',
            name='possession_expected_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 17, 9, 12, 249403, tzinfo=datetime.timezone.utc)),
        ),
    ]
