# Generated by Django 4.2 on 2023-05-12 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0010_alter_propertytype3_possession_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype1',
            name='enquiry_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertytype3',
            name='possession_expected_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 1, 8, 4, 57, 970060, tzinfo=datetime.timezone.utc)),
        ),
    ]
